name: Login to AWS

on: 
    workflow_call: 
        inputs:
            enviroment:
                required: true
                type: string
                description: The environment to deploy to (e.g., dev, staging, prod)
          
        secrets:
            AWS_ACCESS_KEY_ID:
                required: true
            AWS_SECRET_ACCESS_KEY:
                required: true
            AWS_REGION:
                required: true
jobs:
    login:
        runs-on: ubuntu-latest
        steps:

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.aws_access_key_id }}
                aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
                aws-region: ${{ secrets.aws_region }}